#!/bin/sh
#reads the logfile and shows the events on the webpage.
echo -en "HTTP/1.1 200 OK\r\n"
echo -en "Content-Type: text/html; charset=utf-8\r\n"
echo -en "Cache-Control: no-cache\r\n"
echo -en "Connection: close\r\n"
echo -en "\r\n"
echo -en "<BR> <H3>You are coming from $REMOTE_ADDR </H3> <BR>\r\n"

echo -en "<BR><BR> <H1>WIFI AP Events</H1> <BR>\r\n"
echo -en "<BR><BR> <H3>Wifi Access Point Log file: </H3> <BR>\r\n"

#todo: use the a generated logfile (in the same directory?)
#InputFile="/tmp/wifi_http.log"
InputFile="/legato/systems/current/apps/wifiWebAp/read-only/tmp/wifi_http.log"

while IFS= read -r line <&3; do
  echo -en "<font size=\"2\" color=\"green\" > $line </font><br>\r\n"
done 3< "$InputFile";

echo -en "end of log <BR>\r\n"

