#!/bin/sh
echo -en "HTTP/1.1 200 OK\r\n"
echo -en "Content-Type: text/html; charset=utf-8\r\n"
echo -en "Cache-Control: no-cache\r\n"
echo -en "Connection: close\r\n"
echo -en "\r\n"
echo -en "<BR> <H1>Stopping Wifi Access Point<H1> <BR>\r\n"

/legato/systems/current/bin/wifi ap stop >> /tmp/wifiWebAp_startwifiap.log
@echo -en "Stopped Wifi Accesss Point<br>\r\n" >>/legato/systems/current/apps/wifiWebAp/read-only/tmp/wifi_http.log

echo -en "<br>\r\n"
echo -en "<FORM><INPUT Type=\"button\" VALUE=\"Back\" onClick=\"history.go(-1);return true;\"></FORM>\r\n"
echo -en "<br>(end of output<br>\r\n"
